### ISSUE TITLE
Многоканальные кабели из RedPower не имеют рецепта

### ISSUE THREAD

**Issue by Mineteller** [TerraFirmaGreg-New-Horizons/TFG-TerraFirmaCraft-1.12.2#11]
Собственно, многоканальные кабели (bundled cable) из RedPower не имеют рецепта. А они мне очень нужны, вот.

**Comment by Xikaro** [comment]
Не туды

**Comment by Xikaro** [comment]
Сюда писать по тфк и аддонам, тут мы его переписываем

**Comment by Xikaro** [comment]
fixed in 4.2.0
