### ISSUE TITLE
крафт телескопа сложный 

### ISSUE THREAD

**Issue by FriendlyCube** [TerraFirmaGreg-New-Horizons/TFG-TerraFirmaCraft-1.12.2#2]
![изображение_2023-01-12_222442246](https://user-images.githubusercontent.com/112543401/212173435-888e6b07-ed7e-413b-97b9-0bfa2fc0477c.png)
![изображение_2023-01-12_222452794](https://user-images.githubusercontent.com/112543401/212173488-e4a58547-6ccb-4c5d-9f4b-eabf65eda577.png)
сверху крафты  телескопа и штанов для обоих надо алюминий и интегралка 7 из за чего я израсходовал 2 стака алюма :С
поменяй интегралку телескопа пожалуйста

**Comment by Xikaro** [comment]
Ты не туды написал
