### ISSUE TITLE
Связь с космосом потеряна

### ISSUE THREAD

**Issue by TheGalaxx** [TerraFirmaGreg-New-Horizons/TFG-TerraFirmaCraft-1.12.2#9]
На сервере невозможно попасть в космос, при проходе через врата или полетом на ракете я оказываюсь в каком-то неизвестном подпространстве
В одиночке удалось добраться до луны и астероидов, некоторые исследовательские отчеты не работают
![image](https://user-images.githubusercontent.com/105606748/217940099-2369d41f-332f-4806-a442-f1e54949ccbd.png)
![image](https://user-images.githubusercontent.com/105606748/217940143-e491191f-17a2-4458-a736-5bdbe6181679.png)
+ некоторые проблемы с вратами
они есть и активны, но их нет
![image](https://user-images.githubusercontent.com/105606748/217940592-7274a340-4263-4cb0-8421-4026ea6d2d7f.png)
![image](https://user-images.githubusercontent.com/105606748/217940640-728e987c-0c92-4e28-b748-495b2a747279.png)
![image](https://user-images.githubusercontent.com/105606748/217940677-7e28b32f-f57b-4cec-9231-3b3a310ea794.png)
+ у других врат все почти хорошо, они хотя-бы существуют
![image](https://user-images.githubusercontent.com/105606748/217940819-13abf281-67dc-4a58-b0e2-92f519e6fedf.png)
![image](https://user-images.githubusercontent.com/105606748/217940902-dd4af726-072c-4d71-bbe3-4b4efb87b3fb.png)
![image](https://user-images.githubusercontent.com/105606748/217940940-9a0214f0-51fa-4c5a-819a-ed3a05de9d96.png)

**Comment by Xikaro** [comment]
fixed in 4.2.0
